[package]
name = "redis-client"
version = "0.1.0"
edition = "2024"

[dependencies]
fred = "9"
once_cell = "1"
log = "0.4"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"